# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.3
_src_path: https://github.com/jupyterlab/extension-template
author_email: chicocvenancio@gmail.com
author_name: Chico Venancio
has_binder: false
has_settings: false
kind: frontend
labextension_name: labpawspublic
project_short_description: jupyterlab extension to add paws-public links
python_name: labpawspublic
repository: https://github.com/toolforge/labpawspublic.git
test: false

