# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: chicocvenancio@gmail.com
author_name: Chico Venancio
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: labpawspublic
mimetype: ''
mimetype_name: ''
project_short_description: jupyterlab extension to add paws-public links
python_name: labpawspublic
repository: https://github.com/toolforge/labpawspublic.git
test: false
viewer_name: ''

