name: Check Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache checked links
        uses: actions/cache@v4
        with:
          path: ~/.cache/pytest-link-check
          key: ${{ runner.os }}-linkcheck-${{ hashFiles('**/.md') }}-md-links
          restore-keys: |
            ${{ runner.os }}-linkcheck-
      - name: Upgrade packaging dependencies
        run: |
          pip install --upgrade pip setuptools wheel jupyter-packaging~=0.12 --user
      - name: Install Dependencies
        run: |
          pip install .
      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
